### ISSUE TITLE
documentation for batch mode output

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/jNSMR#4]
Would be nice to have a short section in the manual page on how to interpret the results. Field names are mostly self-explanatory, but not all.

**Comment by brownag** [comment]
I added the following to the `newhall_batch()` documentation <<https://ncss-tech.github.io/jNSMR/reference/newhall_batch.html>>:
 - updated description to cover the other S3 methods (rather than just CSV file input)
 - names and descriptions of the major inputs and outputs
 - stub for discussion of different "moisture states" in the Newhall model
 - several related references
 - some initial discussion of nuances of the model; e.g. years are 12 30 day months = 360 days

Is there anything else you were looking to have?

**Comment by dylanbeaudette** [comment]
This is perfect, thanks!
